### ISSUE TITLE
When set to cellular, it does not jump on to wifi.

### ISSUE THREAD

**Issue by cmunk** [klinquist/iOS-VPN-Autoconnect#14]
Hi,

Thanks for the configurator!

I have the following issue:

If I am on cellular, then it will be connected to the VPN over cellular internet. Once I get on my wifi it seems that the VPN over cellular is still active and is the primary internet. Is that  a common thing or have I done something wrong? I would expect the logic to disconnect VPN over cellular and connect over WIFI once the phone is on WIFI.

Thanks.

**Comment by klinquist** [comment]
This is common.  If you had any persistent connections open or downloads in progress, people likely would not want them terminated.
