### ISSUE TITLE
Not Working on MacOS BigSur

### ISSUE THREAD

**Issue by Olivier-Levasseur** [klinquist/iOS-VPN-Autoconnect#15]
Hi, I tried "iOS VPN Profile Generator", on iPhone and it works, but It doesn't work on MacOS BigSur 11.1.
Is there a way to use it on MacOS, too?
This is what happens when I try the profile on MacOS: I set to connect VPN when I'm not connected to my Home WiFi, but when I connect to my iPhone's Tethering to test the created profile, VPN continues to connect and disconnect repeatedly.
What can I do?

**Comment by paulgokk** [comment]
The same for me

**Comment by klinquist** [comment]
>Is there a way to use it on MacOS, too?

Perhaps, someone would need to look up the right plist key/values and make the appropriate changes to the code.

**Comment by Olivier-Levasseur** [comment]
Hi, why is the thread closed since no one gave a solution?

**Comment by mchlbowyer** [comment]
@Olivier-Levasseur I'd guess because this tool is specifically for iOS and the issue relates to macOS which isn't supported. I can't speak for @klinquist, although I'm guessing that's why.

**Comment by Olivier-Levasseur** [comment]
I see. But VPN profile are also present on MacOS, so If someone could manage how to make the same work done for iOS, on MacOS, he will help a lot of people, since I searched for it for days, and there's no actual solution for it.

**Comment by mchlbowyer** [comment]
@Olivier-Levasseur if you are on macOS, have you tried Apple Configurator 2? Depending on your requirements, it may do what you need?

**Comment by Xaositek** [comment]
The difference between iOS and macOS is that within the Network Preferences, you can actually configure a VPN connection right there.

This is contrast to iOS in which through a VPN Profile is the only way to setup this service properly.

**Comment by paulgokk** [comment]
According to this [document](https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf) this profile should work on both iOS and MacOS. So I expected it to work on MacOS too.
On my MacOS Big Sur VPN is trying to connect and immediately disconnects in an endless loop.
Although, if I manually connect to a VPN that was created by the installed profile, it connects and works.

**Comment by Olivier-Levasseur** [comment]
> @Olivier-Levasseur if you are on macOS, have you tried Apple Configurator 2? Depending on your requirements, it may do what you need?

yes, tried but same error using the iOS profile

**Comment by mchlbowyer** [comment]
@Olivier-Levasseur That would suggest that it's an issue with Big Sur then, and not this profile generator if the Apple Configurator is giving you the same error.

**Comment by Olivier-Levasseur** [comment]
> The difference between iOS and macOS is that within the Network Preferences, you can actually configure a VPN connection right there.
> 
> This is contrast to iOS in which through a VPN Profile is the only way to setup this service properly.

actually you can set up a L2TP VPN connection on iOS the same way you do on MacOS. Not necessary you have to import a VPN profile; the advantage of importing the klinquist's profile is that you can have VPN on iOS with rules (like "use VPN when not on home wi-fi").

**Comment by Olivier-Levasseur** [comment]
> @Olivier-Levasseur That would suggest that it's an issue with Big Sur then, and not this profile generator if the Apple Configurator is giving you the same error.

yeah, I'm not an expert about it, so I cannot say. Maybe a few edit and the profile is ready for MacOS. Don't know :/

**Comment by Olivier-Levasseur** [comment]
> According to this [document](https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf) this profile should work on both iOS and MacOS. So I expected it to work on MacOS too.
> On my MacOS Big Sur VPN is trying to connect and immediately disconnects in an endless loop.
> Although, if I manually connect to a VPN that was created by the installed profile, it connects and works.

yes, same problem of "connect/disconnect" loop. I found it amazing on iOS because right after I leave home I'm connected to VPN without doing anything. I hope they'll do it also for MacOS
