### ISSUE TITLE
Consecutive profiles

### ISSUE THREAD

**Issue by luc-ass** [klinquist/iOS-VPN-Autoconnect#6]
Hey there,

thank you very much for creating this tool! I just noticed that once you download a profile, further changes are not applied to consecutive downloads. So you have to reload the page for every new profile. Can you reproduce this behavior?

Thanks, Lucas

**Comment by antoniodowling** [comment]
I had the same experience, and almost went mad trying to understand why the subsequent profiles I was generating were not different from the first. Thank you for pointing this out!

Created a pull request to fix. @klinquist is all over it. :)
