### ISSUE TITLE
Is the configurater actual for iOS 11.x+

### ISSUE THREAD

**Issue by theodormachnich** [klinquist/iOS-VPN-Autoconnect#7]
Hi,

I was setting up a  vpn.mobileconfig file and sent them to my mail address.
If want import the file, also over my website I get always a error "Safari can't open and install this profile (unknown error).
If I use this https://gist.github.com/noestreich/60f4248564e4801365183b79dbfce186#file-fritzboxvpn-mobileconfig-xml it works out of the box.

Something seems to be wrong in the generated file.

Any idea?

Best Theo

**Comment by steam3d** [comment]
It is actual for IOS13 too

**Comment by klinquist** [comment]
Working on the latest iOS14, perhaps an error in your input?
