### ISSUE TITLE
Send all Traffic?

### ISSUE THREAD

**Issue by kupton44** [klinquist/iOS-VPN-Autoconnect#8]
Is it possible to add the "Send all Traffic" option to on or off

**Comment by kupton44** [comment]
OverridePrimary is the name of the option.  Thanks.

**Comment by fakewaffle** [comment]
I see the option `OverridePrimary` under the excluded wifi networks, but should it go somewhere else to force all traffic thru the vpn when not on wifi?

**Comment by klinquist** [comment]
Fixed by https://github.com/klinquist/iOS-VPN-Autoconnect/commit/56a79d91bcb646a0400431b2983038346f6f30f9
